services:
  postgres:
    image: postgres:15
    container_name: postgres_chenga
    restart: always
    environment:
      POSTGRES_USER: chenga 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chenga_ecommerce
    ports:
      - "127.0.0.1:5460:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
